---
# tasks file for base
- name: Install Docker packages
  remote_user: root
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
  tags:
    - docker

- name: Add Dockers official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0755'
  tags:
    - docker

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags:
    - docker

- name: Install Docker Compose
  remote_user: root
  ansible.builtin.apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes
  tags:
    - docker