name: Docker image build/push to DockerHub and deploy to VM

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Python (for Ansible)
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ansible and collections
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jasmar2/express-test-app:0.1

      - name: Save deploy SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > gh_actions_key
          chmod 600 gh_actions_key

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./ansible/inventory ./ansible/site.yml
